version: '3.4'

services:
  hepsiburada.marsrover.application:
    image: ${DOCKER_REGISTRY-}hepsiburadamarsroverapplication
    build:
      context: .
      dockerfile: Hepsiburada.MarsRover.Application/Dockerfile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1

volumes:
    elasticsearch-data: